In [41]:
import numpy as np
import vega_datasets

In [2]:
# Accessing datasets available in vega
dir(vega_datasets.data)

['7zip',
 'airports',
 'annual_precip',
 'anscombe',
 'barley',
 'birdstrikes',
 'budget',
 'budgets',
 'burtin',
 'cars',
 'climate',
 'co2_concentration',
 'countries',
 'crimea',
 'disasters',
 'driving',
 'earthquakes',
 'ffox',
 'flare',
 'flare_dependencies',
 'flights_10k',
 'flights_200k',
 'flights_20k',
 'flights_2k',
 'flights_3m',
 'flights_5k',
 'flights_airport',
 'gapminder',
 'gapminder_health_income',
 'gimp',
 'github',
 'graticule',
 'income',
 'iowa_electricity',
 'iris',
 'jobs',
 'la_riots',
 'londonBoroughs',
 'londonCentroids',
 'londonTubeLines',
 'lookup_groups',
 'lookup_people',
 'miserables',
 'monarchs',
 'movies',
 'normal_2d',
 'obesity',
 'ohlc',
 'points',
 'population',
 'population_engineers_hurricanes',
 'seattle_temps',
 'seattle_weather',
 'sf_temps',
 'sp500',
 'stocks',
 'udistrict',
 'unemployment',
 'unemployment_across_industries',
 'uniform_2d',
 'us_10m',
 'us_employment',
 'us_state_capitals',
 'volcano',
 'weather',
 'weball26',
 'wheat',

In [3]:
df = vega_datasets.data.jobs()
df

job    sex  year  count      perc
0     Accountant / Auditor    men  1850    708  0.000131
1     Accountant / Auditor    men  1860   1805  0.000214
2     Accountant / Auditor    men  1870   1310  0.000100
3     Accountant / Auditor    men  1880   2295  0.000125
4     Accountant / Auditor    men  1900  11753  0.000396
...                    ...    ...   ...    ...       ...
7645                Welder  women  1960  28594  0.000329
7646                Welder  women  1970  48083  0.000440
7647                Welder  women  1980  57920  0.000451
7648                Welder  women  1990  36224  0.000243
7649                Welder  women  2000  63197  0.000376

[7650 rows x 5 columns]

In [ ]:
# Displaying all rows of the df 
print(df.to_string())

In [43]:
# Create an array of ten zeroes
x = np.zeros(10)
x, type(x)
# Difference between list & array - list can have different datatypes whereas array should have the same datatype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), numpy.ndarray)

In [10]:
x[5]= 10
x
# Though the value is given as an integer, it is converted to a float

array([ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.])

In [ ]:
x[7]='hi'
# The value is given as a string and it will throw an error as python can't convert string to float

In [13]:
x.size

10

In [14]:
# Creating a range of values from 10 till 49
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [39]:
# Creating a range of value from 300 till 286
x = np.arange(300,285,-1)
x

array([300, 299, 298, 297, 296, 295, 294, 293, 292, 291, 290, 289, 288,
       287, 286])

In [15]:
# Creating a range of values from 10 till 49 with an increment of 5 & displaying it in a 2*4 matrix
x=np.arange(10,50,5).reshape(2,4)
x

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [23]:
# Displaying the position of the non zero values
x =[1,2,3,0,4]
y=np.nonzero(x)
y
# np.nonzero will return the index of the non zero values 
# whereas np.zeros will create an array of zeros

(array([0, 1, 2, 4]),)

In [24]:
# Creating an identity matrix of 4*4
x = np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# Creating a diaganol matrix
y = np.diag([1,2,3])
y

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [30]:
# Creating a diagonal matrix with values starting from the kth position
y = np.diag([1,2,3],k=3)
y

array([[0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [32]:
x = np.array([2,3])
x

array([2, 3])

In [33]:
# Creating an array by repeating x 3 times
np.tile(x,3)

array([2, 3, 2, 3, 2, 3])

In [35]:
# Creating an array by repeating it 2 times in rows & 3 times in columns
np.tile(x,[2,3])

array([[2, 3, 2, 3, 2, 3],
       [2, 3, 2, 3, 2, 3]])

In [36]:
y = np.array([[6,4],[2,5]])
y

array([[6, 4],
       [2, 5]])

In [40]:
z = np.tile(y,[3,4])
z
# [6,4],[2,5] combination repeated 3 times in rows & 4 times in columns

array([[6, 4, 6, 4, 6, 4, 6, 4],
       [2, 5, 2, 5, 2, 5, 2, 5],
       [6, 4, 6, 4, 6, 4, 6, 4],
       [2, 5, 2, 5, 2, 5, 2, 5],
       [6, 4, 6, 4, 6, 4, 6, 4],
       [2, 5, 2, 5, 2, 5, 2, 5]])

In [38]:
z.size

48

In [ ]:
y.shape

(6, 8)