In [2]:
import numpy as np

In [3]:
# Generating 6 random numbers between 0 and 1
x = np.random.random(6)
x

array([0.93702908, 0.41556371, 0.62831745, 0.22021926, 0.82077743,
       0.52272994])

In [5]:
# Generating random numbers between 0 and 1 in 2*3 matrix
x = np.random.random([2,3])
x

array([[0.90079974, 0.23222773, 0.76730724],
       [0.08288293, 0.60248384, 0.35878058]])

In [6]:
y = x*500
y

array([[450.3998683 , 116.11386582, 383.65361823],
       [ 41.44146457, 301.24192036, 179.39028965]])

In [7]:
# Generating a random number between 0-20
x = np.random.randint(20)
x

18

In [8]:
# Generating 3 random numbers between 0-20
x = np.random.randint(20, size=3)
x

array([19, 18,  1])

In [9]:
# Generating 2 random numbers between 10-20
x = np.random.randint(10,20,size=2)
x

array([10, 15])

In [18]:
# Generating random number between 23-330 in a 2*3 matrix (Not including 330)
x = np.random.randint(23,330,size=(2,3))
print(x, x.max())

[[268 142 167]
 [273 142 248]] 273


In [28]:
#  Generating 1s in a 5*5 matrix
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
# Changing the inside to 0s of a 5*5 matrix containing 1s
n1 = 5 
n2 = 5
for i in range(0,n1):
  for j in range(0,n2):
    if(i==0 or j==0 or i==n1-1 or j==n2-1):
      pass
    else:
      x[i][j]=0
x
# Positions - x[i][j], first position - x[0][0], second position - x[0][1] & so on
# First row i is 0, last row i is 4 (n1-1), first column j is 0, last column j is 4 (n2-1)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
# Selecting all columns & rows between 1 and -1 and posting the value 66
x = np.ones((5,5))
x[1:-1] = 66
x

array([[ 1.,  1.,  1.,  1.,  1.],
       [66., 66., 66., 66., 66.],
       [66., 66., 66., 66., 66.],
       [66., 66., 66., 66., 66.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [39]:
# Increasing the pad_width by 1 and filling it with values 89
y=np.pad(x,pad_width=1,mode="constant",constant_values=89)
y

array([[89., 89., 89., 89., 89., 89., 89.],
       [89.,  1.,  1.,  1.,  1.,  1., 89.],
       [89., 66., 66., 66., 66., 66., 89.],
       [89., 66., 66., 66., 66., 66., 89.],
       [89., 66., 66., 66., 66., 66., 89.],
       [89.,  1.,  1.,  1.,  1.,  1., 89.],
       [89., 89., 89., 89., 89., 89., 89.]])

In [41]:
# Increasing the pad_width by 1 and duplicating it with values in the edge
y=np.pad(x,pad_width=1,mode="edge")
y

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [66., 66., 66., 66., 66., 66., 66.],
       [66., 66., 66., 66., 66., 66., 66.],
       [66., 66., 66., 66., 66., 66., 66.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [47]:
x = np.random.randint(20, size = (2,3))
x

array([[ 8,  2,  7],
       [ 8,  7, 16]])

In [48]:
# Increasing the pad_width by 1 and filling the maximum value of each row/column in the sides
y = np.pad(x,pad_width=1,mode="maximum")
y
#Maximum value on each row will be placed on the pad

array([[16,  8,  7, 16, 16],
       [ 8,  8,  2,  7,  8],
       [16,  8,  7, 16, 16],
       [16,  8,  7, 16, 16]])

In [49]:
# Increasing the pad_width by 2 and filling the minimum value of each row/column in the sides
y=np.pad(x,pad_width=2,mode="minimum")
y

array([[ 2,  2,  8,  2,  7,  2,  2],
       [ 2,  2,  8,  2,  7,  2,  2],
       [ 2,  2,  8,  2,  7,  2,  2],
       [ 7,  7,  8,  7, 16,  7,  7],
       [ 2,  2,  8,  2,  7,  2,  2],
       [ 2,  2,  8,  2,  7,  2,  2]])

In [51]:
y=np.pad(x,pad_width=1,mode="reflect")
y

array([[ 7,  8,  7, 16,  7],
       [ 2,  8,  2,  7,  2],
       [ 7,  8,  7, 16,  7],
       [ 2,  8,  2,  7,  2]])

In [52]:
y=np.pad(x,pad_width=1,mode="symmetric")
y

array([[ 8,  8,  2,  7,  7],
       [ 8,  8,  2,  7,  7],
       [ 8,  8,  7, 16, 16],
       [ 8,  8,  7, 16, 16]])

In [53]:
y=np.pad(x,pad_width=1,mode="wrap")
y
# Like wrapping a paper

array([[16,  8,  7, 16,  8],
       [ 7,  8,  2,  7,  8],
       [16,  8,  7, 16,  8],
       [ 7,  8,  2,  7,  8]])

In [54]:
y=np.pad(x,pad_width=1,mode="linear_ramp")
y

array([[ 0,  0,  0,  0,  0],
       [ 0,  8,  2,  7,  0],
       [ 0,  8,  7, 16,  0],
       [ 0,  0,  0,  0,  0]])

In [59]:
# Posting 50 values with equal intervals between 0 & 50
x=np.linspace(0,50,50)
x

array([ 0.        ,  1.02040816,  2.04081633,  3.06122449,  4.08163265,
        5.10204082,  6.12244898,  7.14285714,  8.16326531,  9.18367347,
       10.20408163, 11.2244898 , 12.24489796, 13.26530612, 14.28571429,
       15.30612245, 16.32653061, 17.34693878, 18.36734694, 19.3877551 ,
       20.40816327, 21.42857143, 22.44897959, 23.46938776, 24.48979592,
       25.51020408, 26.53061224, 27.55102041, 28.57142857, 29.59183673,
       30.6122449 , 31.63265306, 32.65306122, 33.67346939, 34.69387755,
       35.71428571, 36.73469388, 37.75510204, 38.7755102 , 39.79591837,
       40.81632653, 41.83673469, 42.85714286, 43.87755102, 44.89795918,
       45.91836735, 46.93877551, 47.95918367, 48.97959184, 50.        ])

In [60]:
x= np.linspace(1,50,50)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [61]:
# Computing the product of two vectors
x = np.outer([2,3],[4,9])
x
# 2*4 and 2*9 in first row | 3*4 and 3*9 in second row

array([[ 8, 18],
       [12, 27]])

In [63]:
x = np.outer([[2,3],[1,5]],[[2,5],[4,9]])
x

array([[ 4, 10,  8, 18],
       [ 6, 15, 12, 27],
       [ 2,  5,  4,  9],
       [10, 25, 20, 45]])

In [64]:
x=np.arange(1,90)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89])

In [65]:
# Splitting the array with 89 values into 4
x_split = np.array_split(x,4)
x_split
# Total 89 values first 22 values to each row and then remaining added to the first row

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23]),
 array([24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45]),
 array([46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
        63, 64, 65, 66, 67]),
 array([68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89])]

In [67]:
# Generating a random sample
x = np.random.choice(['arun','ashok','ram'])
x

'arun'

In [68]:
# Generating a random sample of size 2
x = np.random.choice(['arun','ashok','ram'],size=2)
x

array(['arun', 'ashok'], dtype='<U5')

In [75]:
# Generating a random sample of size 2 based on probability of occurence  
x= np.random.choice(['arun','ashok','ram','guru','prasanth'],p=[0.4,0.2,0.2,0.1,0.1],size=4)
x
# Total probability should add upto 1

array(['ashok', 'arun', 'ram', 'ashok'], dtype='<U8')

In [77]:
# Finding the index value based on condition
w = np.where(x=='ashok')
w
# arun is found in 0th & 3rd positions

(array([0, 3]),)

In [79]:
# Creating one of the permutations of x
x=np.array([5,6,7,8,9])
np.random.shuffle(x)
x

array([9, 8, 6, 5, 7])

In [92]:
# Returning all possible permutations of size 2 as tuples
import itertools as it
per = it.permutations(x,2)
for i in list(per):
  print(i)
# Position matters in a permutation & doesn't matter in combinations

(0, 1)
(0, 2)
(0, 3)
(0, 4)
(0, 8)
(1, 0)
(1, 2)
(1, 3)
(1, 4)
(1, 8)
(2, 0)
(2, 1)
(2, 3)
(2, 4)
(2, 8)
(3, 0)
(3, 1)
(3, 2)
(3, 4)
(3, 8)
(4, 0)
(4, 1)
(4, 2)
(4, 3)
(4, 8)
(8, 0)
(8, 1)
(8, 2)
(8, 3)
(8, 4)


In [89]:
x=np.array([0,1,2,3,4,8])
password = (8,4,2,1)
per=it.permutations(x,4)
# per is all possible permutaions of x with length 4

In [90]:
# Finding the number of trials generated to find the password 
j = 0 
for i in list(per):
  if(i==password):
    break
  j=j+1
print(j)

355


In [ ]:
x=np.array([0,1,2,3,4,9,8])
com=it.combinations(x,5)
for i in list(com):
  print(i)
# Combination will be lower in number compared to permutation as the position of values don't matter

(0, 1, 2, 3, 4)
(0, 1, 2, 3, 9)
(0, 1, 2, 3, 8)
(0, 1, 2, 4, 9)
(0, 1, 2, 4, 8)
(0, 1, 2, 9, 8)
(0, 1, 3, 4, 9)
(0, 1, 3, 4, 8)
(0, 1, 3, 9, 8)
(0, 1, 4, 9, 8)
(0, 2, 3, 4, 9)
(0, 2, 3, 4, 8)
(0, 2, 3, 9, 8)
(0, 2, 4, 9, 8)
(0, 3, 4, 9, 8)
(1, 2, 3, 4, 9)
(1, 2, 3, 4, 8)
(1, 2, 3, 9, 8)
(1, 2, 4, 9, 8)
(1, 3, 4, 9, 8)
(2, 3, 4, 9, 8)
